openapi: 3.0.0
info:
  title: AutoWorld Georgia production
  version: 1.1.0
paths:
  /api/{proxy+}:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: __YC_CONTAINER_ID__
        service_account_id: __YC_DEPLOY_SA_ID__
      parameters:
        - explode: false
          in: path
          name: proxy
          required: true
          schema:
            type: string
          style: simple

  /:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: __AWG_STATIC_BUCKET__
        object: index.html
        service_account_id: __YC_DEPLOY_SA_ID__

  /{proxy+}:
    get:
      parameters:
        - explode: false
          in: path
          name: proxy
          required: true
          schema:
            type: string
          style: simple
      x-yc-apigateway-integration:
        type: object_storage
        bucket: __AWG_STATIC_BUCKET__
        object: '{proxy}'
        error_object:
          object: index.html
          statusCode: 200
        service_account_id: __YC_DEPLOY_SA_ID__
